### ISSUE TITLE
fix pls

### ISSUE THREAD

**Issue by darkzone964** [champmq/GoogleFU#1]
python3 GoogleFU.py
Traceback (most recent call last):
  File "/home/dark/Desktop/tools/GoogleFU/GoogleFU.py", line 2, in <module>
    from modules.search import Search
  File "/home/dark/Desktop/tools/GoogleFU/modules/search.py", line 1, in <module>
    from googlesearch import search as gsearch
ImportError: cannot import name 'search' from 'googlesearch' (/usr/local/lib/python3.11/dist-packages/googlesearch/__init__.py)

**Comment by Jaynornj** [comment]
You need to import that requires libraries @darkzone964

**Comment by darkzone964** [comment]
i download the txt file and i search for the library but its not working

**Comment by tiagolopez** [comment]
python3 GoogleFU.py
/Library/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/tiago/GoogleFU.py': [Errno 2] No such file or directory

Why? I installed everything smoothly

**Comment by tiagolopez** [comment]
im on MacOS bth. M1

**Comment by champmq** [comment]
R u in the folder when u run that command?

**Comment by airborne-commando** [comment]
Did you create a virtual python environment @darkzone964?

```
Python3 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt
python3 GoogleFU.py
```

That's what I did to get this to work under linux; windows may be different tho.
